version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"
    groups:
      actions:
        patterns:
          - "*"
  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - update-types: ["version-update:semver-patch"]
        dependency-name: "*"
    pull-request-branch-name:
      separator: "-"
    groups:
      pip:
        patterns:
          - "*"
  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"
    groups:
      docker:
        patterns:
          - "*"
