name: CI tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tool: black
            args: --check
          - tool: flake8
            args: --ignore=E501,W503
          - tool: isort
            args: --check --diff

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install ${{ matrix.tool }}
        run: |
          python -m pip install -U pip
          python -m pip install ${{ matrix.tool }}

      - name: Run ${{ matrix.tool }}
        run: |
          ${{ matrix.tool }} ${{ matrix.args }} .

  check-static-typing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dev requirements
        run: |
          python -m pip install -r dev-requirements.txt

      - name: Run mypy static checker
        run: |
          mypy helm_bot/

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version  }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r dev-requirements.txt

      - name: Install helm-bot
        run: |
          python setup.py install

      - name: Run tests
        run: |
          python -m coverage run -m pytest -vvv

      - name: Generate coverate report
        run: |
          coverage report && coverage html

      - name: Upload htmlcov dir as artifact
        if: |
          (matrix.python_version == '3.9') &&
          (github.event_name == 'push') &&
          (github.ref == 'refs/heads/main')
        uses: actions/upload-artifact@v2
        with:
          name: htmlcov
          path: htmlcov/

  update-badge:
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download htmlcov artifact
        uses: actions/download-artifact@v2
        with:
          name: htmlcov
          path: htmlcov

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run:
          python -m pip install -U pip bs4 rich

      - name: Run script to update badge metadata
        run: |
          python update_coverage_badge.py --dry-run ${{ github.event_name == 'pull_request' }}

      - name: Add and commit the edited metadata file
        if: (github.event_name == 'push') && (github.ref == 'refs/heads/main')
        uses: EndBug/add-and-commit@v4
        with:
          add: 'badge_metadata.json'
          author_name: CI User
          author_email: ci-user@github.local
          message: 'Update coverage badge metadata'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
