name: CI tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Also run weekly, to make sure nothing has broken in the interim
  schedule:
    - cron: "0 0 * * 1"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: codecov
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version  }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r dev-requirements.txt

      - name: Install helm-bot
        run: |
          python setup.py install

      - name: Run tests
        run: |
          python -m coverage run -m pytest -vvv --color=yes

      - name: Generate coverate report
        run: |
          coverage report && coverage xml

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  run-test-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install package
        run: |
          python -m pip install -e .

      - name: Run helm-bot
        run: helm-bot
        env:
          CHART_PATH: "tests/assets/test-chart"
