name: Build Docker Image

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Parse image tag
        id: parse_image_tag
        shell: python
        run: |
          tag = "${{ github.head_ref }}".replace("/", "-")
          print(f"::set-output name=image_tag::{tag}")

      - name: Echo tag
        run: |
          echo "${{ steps.parse_image_tag.outputs.image_tag }}"

      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        uses: docker/build-push-action@v3.0.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.repository }}:${{ steps.parse_image_tag.outputs.image_tag }}
